[package]
name = "patina_ffs_extractors"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "UEFI section extractor implementations."
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
patina = { workspace = true }
patina_ffs = { workspace = true }
brotli-decompressor = { workspace = true, optional = true }
alloc-no-stdlib = { workspace = true, optional = true }
crc32fast = { workspace = true, optional = true }
lzma-rust2 = { workspace = true, optional = true, default-features = false }

[features]
default = ["brotli", "crc32", "lzma"]
std = []
brotli = ["dep:brotli-decompressor", "dep:alloc-no-stdlib"]
crc32 = ["dep:crc32fast"]
lzma = ["dep:lzma-rust2"]
# All non-std features to test in CI
ci_features = ["brotli", "crc32", "lzma"]

[dev-dependencies]
lzma-rust2 = { workspace = true }
