[package]
name = "patina_stacktrace"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "Stack Tracing library."

[lints]
workspace = true

[dependencies]
cfg-if = { workspace = true }
log = { workspace = true }

[features]
std = []
doc = []
# All non-std features to test in CI
ci_features = []
