[config]
default_to_workspace = false

[env]
ARCH = "X64"
NO_STD_FLAGS = "--profile ${RUSTC_PROFILE} --target x86_64-unknown-uefi -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -Zunstable-options --timings=html"

[env.development]
RUSTC_PROFILE = "dev"
RUSTC_TARGET = "debug"

[env.release]
RUSTC_PROFILE = "release"
RUSTC_TARGET = "release"

[tasks.build]
clear = true
command = "cargo"
args = ["build", "@@split(CARGO_MAKE_TASK_ARGS,;)", "@@split(NO_STD_FLAGS, )"]
