[package]
name = "patina_test"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "Component and framework for on-system unit testing."

[lints]
workspace = true

[dependencies]
linkme = { workspace = true }
log = { workspace = true }
patina = { workspace = true, features = ["alloc"] }
patina_macro = { workspace = true }
spin = { workspace = true }

[features]
test-runner = ["patina_macro/enable_patina_tests"]
# All non-std features to test in CI
ci_features = ["test-runner"]
