[package]
name = "patina_samples"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "Sample components for testing and reference."
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
log = { workspace = true }
patina = { workspace = true }
patina_macro = { workspace = true }
patina_smbios = { workspace = true }

[features]
std = []
# All non-std features to test in CI
ci_features = []
